version: "3"
services:
  central-party-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: central-party-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://central-party-agent:8000"
      ACAPY_LABEL: "Central Party Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
      WEBHOOK_URL: "http://central-party-webhook:5000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode \
        --webhook-url 'http://central-party-webhook:5000'"
    ]
    ports:
      - "8001:8001"
  
  central-party-webhook:
    image: python:3.8-slim
    container_name: central-party-webhook
    volumes:
      - ./src:/app
      - ./data:/data
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python central-party.py"]
    ports:
      - "5000:5000"

  fl-client-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: fl-client-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://fl-client-agent:8100"
      ACAPY_LABEL: "FL Client Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8101"
      AGENT_PORT: "8100"
      WEBHOOK_URL: "http://fl-client-webhook:5000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8101 \
        --inbound-transport http '0.0.0.0' 8100 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode \
        --webhook-url 'http://fl-client-webhook:5000'"
    ]
    ports:
      - "8101:8101"
  
  fl-client-webhook:
    image: python:3.8-slim
    container_name: fl-client-webhook
    volumes:
      - ./src:/app
      - ./data:/data
    working_dir: /app
    command: ["sh", "-c", "pip install -r requirements.txt && python fl-client.py"]
    ports:
      - "5001:5000"
