version: "3"
services:
  alice-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: alice-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://alice-agent:8000"
      ACAPY_LABEL: "Alice Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
      WEBHOOK_URL: "http://alice-webhook:5000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode \
        --webhook-url 'http://alice-webhook:5000'"
    ]
    ports:
      - "8001:8001"
  
  alice-webhook:
    image: python:3.8-slim
    container_name: alice-webhook
    volumes:
      - ./webhooks/alice/webhook.py:/app/webhook.py
    working_dir: /app
    command: ["sh", "-c", "pip install flask && python webhook.py"]
    ports:
      - "5000:5000"

  bob-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: bob-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://bob-agent:8100"
      ACAPY_LABEL: "Bob Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8101"
      AGENT_PORT: "8100"
      WEBHOOK_URL: "http://bob-webhook:5000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8101 \
        --inbound-transport http '0.0.0.0' 8100 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode \
        --webhook-url 'http://bob-webhook:5000'"
    ]
    ports:
      - "8101:8101"
  
  bob-webhook:
    image: python:3.8-slim
    container_name: bob-webhook
    volumes:
      - ./webhooks/bob/webhook.py:/app/webhook.py
    working_dir: /app
    command: ["sh", "-c", "pip install flask && python webhook.py"]
    ports:
      - "5001:5000"
