version: "3"
services:
  alice-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: alice-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://alice-agent:8000"
      ACAPY_LABEL: "Alice Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8001"
      AGENT_PORT: "8000"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8001 \
        --inbound-transport http '0.0.0.0' 8000 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode "
    ]
    ports:
      - "8001:8001"

  bob-agent:
    image: bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
    container_name: bob-agent
    environment:
      ACAPY_ADMIN_INSECURE_MODE: "true"
      ACAPY_AUTO_PROVISION: "true"
      ACAPY_DEBUG_CONNECTIONS: "true"
      ACAPY_ENDPOINT: "http://bob-agent:8100"
      ACAPY_LABEL: "Bob Agent"
      ACAPY_LOG_LEVEL: "info"
      ACAPY_NO_LEDGER: "true"
      ADMIN_PORT: "8101"
      AGENT_PORT: "8100"
    entrypoint: /bin/bash
    command: ["-c",
        "aca-py start \
        --admin '0.0.0.0' 8101 \
        --inbound-transport http '0.0.0.0' 8100 \
        --outbound-transport http \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --admin-insecure-mode "
    ]
    ports:
      - "8101:8101"
