FROM python:3.8-slim

EXPOSE 5000

WORKDIR /app

COPY ./src/lib /app/lib
COPY ./src/requirements.txt /app/requirements.txt
COPY ./src/fl-client.py /app/webhook.py

RUN pip install -r requirements.txt

CMD ["python", "webhook.py"]
